### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mozork01** [Suff99/MC-Gliders#51]
Hey
Fabric 1.20.1
I crashed when lightning struck my glider with the copper upgrade.

[crash-2024-02-07_11.37.33-server.txt](https://github.com/Suff99/MC-Gliders/files/14192600/crash-2024-02-07_11.37.33-server.txt)

**Comment by Mozork01** [comment]
The crash only occurs with the copper upgrade.
The crash occurs when lightning strikes me.

**Comment by Mozork01** [comment]
I tested the copper upgrade with both the Netherite and diamond gliders. In both cases, the game crashes when lightning strikes me.
So the issue arises from the copper upgrade.

**Comment by Suff99** [comment]
Fixed
