### ISSUE TITLE
Glider Incorrectly Rotates on Fabric

### ISSUE THREAD

**Issue by snoandpetals** [Suff99/MC-Gliders#56]
https://github.com/Suff99/MC-Gliders/assets/62764868/b5cd27e1-ddbc-4a45-8d1f-a86df2e69d85

Was tested with Fabric 0.15.7 on 1.20.1 with Sodium, Fabric API, Indium, and Gliders.

**Comment by Suff99** [comment]
Closed by https://github.com/Suff99/MC-Gliders/commit/2cc5c5af0176f0c5a4193ae4851eb0b9b5404510
